<?php
/**
 * LINE CRM Pharmacy - Configuration
 * Generated by Installation Wizard on 2026-01-21 03:09:00
 */

mb_internal_encoding('UTF-8');
mb_http_output('UTF-8');

error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Database
define('DB_HOST', 'localhost');
define('DB_NAME', 'zrismpsz_cny2');
define('DB_USER', 'zrismpsz_cny2');
define('DB_PASS', 'zrismpsz_cny2');

// Application
define('APP_NAME', 'Agentic line');
define('APP_URL', 'https://re-ya.com');
define('BASE_URL', 'https://re-ya.com');
define('TIMEZONE', 'Asia/Bangkok');

// LINE API (ตั้งค่าผ่านหน้า Admin)
define('LINE_CHANNEL_ACCESS_TOKEN', '');
define('LINE_CHANNEL_SECRET', '');

// Table Names
define('TABLE_USERS', 'users');
define('TABLE_GROUPS', 'groups');

date_default_timezone_set(TIMEZONE);