<?php
/**
 * LINE OA Manager - Configuration
 * Generated by Installation Wizard
 */

// Set Thai Timezone
date_default_timezone_set('Asia/Bangkok');

// Set UTF-8 encoding
mb_internal_encoding('UTF-8');
mb_http_output('UTF-8');
header('Content-Type: text/html; charset=utf-8');

// Error reporting
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// Start session
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
// Database Credentials
if (!defined('DB_HOST'))
    define('DB_HOST', 'localhost');
if (!defined('DB_NAME'))
    define('DB_NAME', 'zrismpsz_cny');  // แก้ให้ตรงกับชื่อ database บน hosting ใหม่
if (!defined('DB_USER'))
    define('DB_USER', 'zrismpsz_cny');  // แก้ให้ตรงกับ username ที่สร้าง
if (!defined('DB_PASS'))
    define('DB_PASS', 'zrismpsz_cny'); // แก้เป็นรหัสผ่านที่ตั้งไว้
if (!defined('LIFF_SHARE_ID'))
    define('LIFF_SHARE_ID', '');
if (!defined('LIFF_ID'))
    define('LIFF_ID', ''); // LIFF ID หลัก

// App Configuration
if (!defined('APP_NAME'))
    define('APP_NAME', 'LINECRM');
if (!defined('APP_URL'))
    define('APP_URL', 'https://cny.re-ya.com/');  // แก้เป็น URL ใหม่
if (!defined('BASE_URL'))
    define('BASE_URL', 'https://cny.re-ya.com/'); // แก้เป็น URL ใหม่
if (!defined('APP_VERSION'))
    define('APP_VERSION', '2026.01.23.03'); // Version with video call fix 2
if (!defined('TIMEZONE'))
    define('TIMEZONE', 'Asia/Bangkok');
// LINE API (ตั้งค่าผ่านหน้า Admin)
if (!defined('LINE_CHANNEL_ACCESS_TOKEN'))
    define('LINE_CHANNEL_ACCESS_TOKEN', '');
if (!defined('LINE_CHANNEL_SECRET'))
    define('LINE_CHANNEL_SECRET', '');

// OpenAI (Optional)
if (!defined('OPENAI_API_KEY'))
    define('OPENAI_API_KEY', '');

// Telegram Notifications (Optional)
if (!defined('TELEGRAM_BOT_TOKEN'))
    define('TELEGRAM_BOT_TOKEN', '');
if (!defined('TELEGRAM_CHAT_ID'))
    define('TELEGRAM_CHAT_ID', '');

// Table Names
if (!defined('TABLE_USERS'))
    define('TABLE_USERS', 'users');
if (!defined('TABLE_GROUPS'))
    define('TABLE_GROUPS', 'groups');

// Initialize
date_default_timezone_set(TIMEZONE);
