<?php
/**
 * LINE CRM Pharmacy - Configuration
 * Generated by Installation Wizard on 2026-01-21 03:09:00
 */
error_reporting(E_ALL & ~E_DEPRECATED & ~E_STRICT);

// mb_internal_encoding('UTF-8'); // Deprecated in PHP 8.2+
mb_http_output('UTF-8');
ini_set('default_charset', 'UTF-8');

ini_set('display_errors', 0);
ini_set('log_errors', 1);


if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Database
define('DB_HOST', 'localhost');
define('DB_NAME', 'zrismpsz_cny');
define('DB_USER', 'zrismpsz_cny');
define('DB_PASS', 'zrismpsz_cny');

// Application
define('APP_NAME', 'Agentic line');
define('APP_URL', 'https://cny.re-ya.com');
define('BASE_URL', 'https://cny.re-ya.com');
define('TIMEZONE', 'Asia/Bangkok');

// LINE API (ตั้งค่าผ่านหน้า Admin)
define('LINE_CHANNEL_ACCESS_TOKEN', '');
define('LINE_CHANNEL_SECRET', '');

// Table Names
define('TABLE_USERS', 'users');
define('TABLE_GROUPS', 'groups');
// Next.js API Integration
// URL ของ Next.js app (ปรับตาม environment)
define('NEXTJS_API_URL', 'https://inbox.re-ya.com');
// Secret key สำหรับ authentication (ใช้ค่าเดียวกับ Next.js INTERNAL_API_SECRET)
define('INTERNAL_API_SECRET', 'UIFW4a63EGivOlJi4ulxBmaV+0S5WpS5i3ofQqzIOhI=');

// ============================================================================
// Odoo ERP Integration Configuration
// ============================================================================

// Environment: 'staging' or 'production'
// Force production for cny.re-ya.com
define('ODOO_ENVIRONMENT', 'production');

// Staging Configuration
define('ODOO_STAGING_API_BASE_URL', 'https://stg-erp.cnyrxapp.com');
define('ODOO_STAGING_API_KEY', getenv('ODOO_STAGING_API_KEY') ?: '');
define('ODOO_STAGING_WEBHOOK_SECRET', getenv('ODOO_STAGING_WEBHOOK_SECRET') ?: '');

// Production Configuration
define('ODOO_PRODUCTION_API_BASE_URL', 'https://erp.cnyrxapp.com');
define('ODOO_PRODUCTION_API_KEY', getenv('ODOO_PRODUCTION_API_KEY') ?: '5pG-doAH1EEqHXurM3t466WAgKRYemmK7FANAB74o5A');
define('ODOO_PRODUCTION_WEBHOOK_SECRET', getenv('ODOO_PRODUCTION_WEBHOOK_SECRET') ?: 'cny_reya_webhook_3226e48c7c053b4af44011651f2d3cfb');

// Active Configuration (based on environment)
define(
    'ODOO_API_BASE_URL',
    ODOO_ENVIRONMENT === 'production'
    ? ODOO_PRODUCTION_API_BASE_URL
    : ODOO_STAGING_API_BASE_URL
);

define(
    'ODOO_API_KEY',
    ODOO_ENVIRONMENT === 'production'
    ? ODOO_PRODUCTION_API_KEY
    : ODOO_STAGING_API_KEY
);

define(
    'ODOO_WEBHOOK_SECRET',
    ODOO_ENVIRONMENT === 'production'
    ? ODOO_PRODUCTION_WEBHOOK_SECRET
    : ODOO_STAGING_WEBHOOK_SECRET
);

// Webhook verification tolerances (temporary legacy bridge defaults allow +7h skew)
$webhookToleranceEnv = getenv('ODOO_WEBHOOK_TOLERANCE_SECONDS');
define(
    'ODOO_WEBHOOK_TOLERANCE_SECONDS',
    $webhookToleranceEnv !== false ? (int) $webhookToleranceEnv : 300
);

$allowLegacyDriftEnv = getenv('ODOO_WEBHOOK_ALLOW_LEGACY_DRIFT');
define(
    'ODOO_WEBHOOK_ALLOW_LEGACY_DRIFT',
    $allowLegacyDriftEnv === false
        ? true
        : !in_array(strtolower((string) $allowLegacyDriftEnv), ['0', 'false', 'no'], true)
);

$legacyDriftEnv = getenv('ODOO_WEBHOOK_LEGACY_DRIFT_SECONDS');
define(
    'ODOO_WEBHOOK_LEGACY_DRIFT_SECONDS',
    $legacyDriftEnv !== false ? (int) $legacyDriftEnv : (7 * 3600)
);

$legacyDriftToleranceEnv = getenv('ODOO_WEBHOOK_LEGACY_DRIFT_TOLERANCE');
define(
    'ODOO_WEBHOOK_LEGACY_DRIFT_TOLERANCE',
    $legacyDriftToleranceEnv !== false ? (int) $legacyDriftToleranceEnv : 120
);

// Odoo API Settings
define('ODOO_API_TIMEOUT', 30); // seconds
define('ODOO_API_RATE_LIMIT', 60); // requests per minute
define('ODOO_WEBHOOK_TIMEOUT', 5); // seconds - must respond within this time

// Odoo Product API credentials (for /ineco_gc endpoints)
$defaultCnyOdooApiUser = ODOO_ENVIRONMENT === 'production' ? 'webapi_user2@cny.co' : '';
$defaultCnyOdooUserToken = ODOO_ENVIRONMENT === 'production'
    ? '@ewNI*4X*/4t9vgMds2Gzs3j=VG%q%ERYM-1A/utT0#CUZ&UR&$pwvuxj!MNUcruJ@RZ/p7$uN*fdqE6xktQdGxGov%?L0@@CekhyzeROSv2/qmj&%G-vlHq$4V8&AHC/XkxI$Tgkbq3p/6faPvf8wjIP#hfZM7GimVkXbvpvsrfZKOCGk?ldTpL9=5qI-eCVs29xIyr0'
    : '';
define('CNY_ODOO_API_USER', getenv('CNY_ODOO_API_USER') ?: (getenv('ODOO_PRODUCTION_API_USER') ?: $defaultCnyOdooApiUser));
define('CNY_ODOO_USER_TOKEN', getenv('CNY_ODOO_USER_TOKEN') ?: (getenv('ODOO_PRODUCTION_USER_TOKEN') ?: $defaultCnyOdooUserToken));

// Webhook URL (for Odoo team reference)
define('ODOO_WEBHOOK_URL', APP_URL . '/api/webhook/odoo.php');

// LINE Account Mode for Odoo Integration
// 'shared' = ค้นหา user จากทุก line_account_id ในระบบ
define('ODOO_LINE_ACCOUNT_MODE', 'shared');

date_default_timezone_set(TIMEZONE);